apiVersion: apps/v1
kind: Deployment
metadata:
  name: internshipgolang
  labels:
    app: internshipgolang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internshipgolang
  template:
    metadata:
      labels:
        app: internshipgolang
    spec:
      containers:
        - name: internshipgolang
          image: amserdion/internshipgolang:sha-c76067f
          ports:
            - containerPort: 8081
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: db_url
                  name: data-configx
            - name: SUPERADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: mail
                  name: data-configx
            - name: SUPERADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: data-configx
