apiVersion: v1
kind: Service
metadata:
  name: golang
spec:
  type: LoadBalancer
  selector:
    app: golang
  ports:
    - protocol: TCP
      name: rest
      port: 8080
      targetPort: 8080
    - protocol: TCP 
      name: graph
      port: 8081
      targetPort: 8081
