apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atoss-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: develop
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argoyaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true