apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internshipgolang
spec:
  project: default
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: golang
    path: argogolang
  destination:
    server: https://kubernetes.default.svc
    namespace: golang
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true