apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: vue
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argovueyaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true