apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bumbaruflaviusgabriel/keycloak:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
          requests:
            memory: "150Mi"
            cpu: "100m"
            
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            configMapKeyRef:
              key: keycloak_admin
              name: configmap

        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: keycloak_password
              name: configmap

        - name: KEYCLOAK_REALM_IMPORT
          valueFrom:
            configMapKeyRef:
              key: keycloak_import
              name: configmap

        - name: KEYCLOAK_URL 
          valueFrom:
            configMapKeyRef:
              key: keycloak_url
              name: configmap

        ports:
        - name: http
          containerPort: 8084
