apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  selector:
    app: keycloak
  type: LoadBalancer