apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis_url: redis.node.svc.cluster.local
  keycloak_host:  http://localhost:8082
  golang_host: http://golang-service.golang.svc.cluster.local:8081
