apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: vue
    path: keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: argovueyaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true