apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-vue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: main
    path: vue
  destination:
    server: https://kubernetes.default.svc
    namespace: vue
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true