apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-redis
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://github.com/princekhanna13/internshipargo.git
    targetRevision: main
    path: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: node
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true